import { Card, CardContent } from '@/components/ui/card';

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-32">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold font-headline mb-8 text-slate-900">Terms of Service</h1>
        <Card className="border-none shadow-xl rounded-[2rem] overflow-hidden">
          <CardContent className="p-8 md:p-12 space-y-6 text-slate-700 leading-relaxed">
            <p>By using ScriptaNova, you agree to the following terms:</p>
            <section>
              <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Copyrights</h2>
              <p>All rights to works created using our tools belong to the author. ScriptaNova does not claim any share in your copyrights.</p>
            </section>
            <section>
              <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Use of AI</h2>
              <p>You understand that content is generated by a neural network and may require verification for factual accuracy.</p>
            </section>
            <section>
              <h2 className="text-2xl font-bold text-slate-900 mb-4">3. Restrictions</h2>
              <p>It is prohibited to use the platform to create harmful content or violate intellectual property laws.</p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}